apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: docker-build-workflow-template
  namespace: argo
spec:
  entrypoint: docker-build-workflow
  arguments:
    parameters:
    - name: ssh-url
      value: 'The ssh-url of the repo to build'
    - name: repo-name
      value: 'The name of the repo from git'
  templates:
  - name: docker-build-workflow
    inputs:
      parameters: 
      - name: ssh-url
        default: '{{inputs.parameters.ssh-url}}'
      - name: repo-name
        default: '{{inputs.parameters.repo-name}}'
    steps:
    - - name: git-clone
        templateRef:
          name: git-clone-template
          template: git-clone
        arguments:
          parameters:
          - name: ssh-url
            value: "{{inputs.parameters.ssh-url}}"
      - name: harbor-create-project-wf
        templateRef:
          name: tooling-harbor-create-project-wf-tp
          template: workflow
        arguments:
         parameters:
          - name: repo-name
            value: "{{inputs.parameters.repo-name}}"
    - - name: docker-build
        template: buildkit
        arguments:
          artifacts:
          - name: repo
            from: "{{steps.git-clone.outputs.artifacts.repo}}"
          parameters:
          - name: repo-name
            value: "{{inputs.parameters.repo-name}}"

  - name: buildkit
    inputs:
      parameters:
      - name: repo-name
      artifacts:
      - name: repo
        path: /repo
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/main: unconfined
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "k8s-secrets"
        vault.hashicorp.com/agent-inject-secret-server-url: "k8s/data/configs/server-url"
        vault.hashicorp.com/agent-inject-template-server-url: |
          {{ with secret "k8s/data/configs/server-url" -}}
            export serverurl={{ .Data.data.url }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-config.json: "k8s/data/tooling-harbor-robot-accounts/{{inputs.parameters.repo-name}}"
        vault.hashicorp.com/agent-inject-template-config.json: |
          {{ with secret "k8s/data/tooling-harbor-robot-accounts/{{inputs.parameters.repo-name}}" -}}
            {{ .Data.data.authFile }}
          {{- end }}
    container:
      image: moby/buildkit:master-rootless
      workingDir: /repo
      env:
        - name: BUILDKITD_FLAGS
          value: --oci-worker-no-process-sandbox
        - name: BUILDCTL_CONNECT_RETRIES_MAX
          value: "20"
        - name: DOCKER_CONFIG
          value: /vault/secrets
      command:
        - "/bin/sh"
      args: 
        - "-c"
        - "source /vault/secrets/server-url;
          buildctl-daemonless.sh build --frontend dockerfile.v0 --local context=./src/ --local dockerfile=./.docker/ --output type=image,name=$serverurl/{{inputs.parameters.repo-name}}/{{inputs.parameters.repo-name}},push=true"
