apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-scripts
  namespace: argo
data:
  check-endpoint.sh: |
    #!/bin/bash
    # Pass the name of a service to check ie: sh check-endpoint.sh staging-voting-app-vote
    # Will run forever...
    external_ip=""
    while [ -z $external_ip ]; do
      echo "Waiting for end point..."
      external_ip=$(kubectl get svc $1 --template="{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}" -n $2)
      [ -z "$external_ip" ] && sleep 10
    done
    echo 'End point ready:' && echo $external_ip