apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: utility-get-server-url
  namespace: argo
spec:
  entrypoint: get-server-url
  templates:
  - name: get-server-url
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/main: unconfined
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "k8s-secrets"
        vault.hashicorp.com/agent-inject-secret-server-url: "k8s/data/configs/server-url"
        vault.hashicorp.com/agent-inject-template-server-url: |
          {{ with secret "k8s/data/configs/server-url" -}}
            export serverurl="{{ .Data.data.url }}"
          {{- end }}
    script:
      image: alpine
      command: [/bin/sh]
      source: |
        source /vault/secrets/server-url;
        printf $serverurl;