apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: oauth-enable-wf-tp
  namespace: argo
spec:
  entrypoint: oauth-enable-wf
  podGC:
    strategy: OnWorkflowSuccess
  templates:
    - name: oauth-enable-wf 
      steps:
      - - name: get-server-url
          templateRef:
            name: utility-get-server-url 
            template: get-server-url

        - name: get-kubeconf
          templateRef:
            name: az-aks-cred-template
            template: az-aks-cred

      - - name: oauth-enable
          templateRef:
            name: oauth-enable-single-app-wf-tp
            template: oauth-enable-single-app-wf
          arguments:
            artifacts:
              - name: kube-config
                from: '{{steps.get-kubeconf.outputs.artifacts.kube-config}}'
            parameters:
              - name: server-url
                value: '{{steps.get-server-url.outputs.parameters.server-url}}'
              - name: repo
                value: '{{item.repo}}'
              - name: script
                value: '{{item.script}}'
          withItems: 
          - {
            repo: git@github.com:Open-Dataplatform/tooling-grafana.git,
            script:
              j2 /repo/.setup/oauth-values.j2 -o j2-tmp.yaml;
              argocd app get tooling-grafana -o yaml | yq e .spec.source.helm.values - > tmp.yaml;
              yq eval-all --inplace 'select(fileIndex == 0) * select(fileIndex == 1)' tmp.yaml j2-tmp.yaml;
              argocd app set tooling-grafana --values-literal-file tmp.yaml;
            }
          - {
            repo: git@github.com:Open-Dataplatform/tooling-argo-cd.git,
            script:
              j2 /repo/.setup/oauth-values.j2 -o j2-tmp.yaml;
              argocd app get tooling-argocd -o yaml | yq e .spec.source.helm.values - > tmp.yaml;
              yq eval-all --inplace 'select(fileIndex == 0) * select(fileIndex == 1)' tmp.yaml j2-tmp.yaml;
              argocd app set tooling-argocd --values-literal-file tmp.yaml;
            }

        - name: oauth-harbor
          templateRef:
            name: tooling-harbor-enable-oauth-tp
            template: enable-oauth