apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tooling-harbor-enable-oauth-tp
  namespace: argo
spec:
  entrypoint: enable-oauth
  templates:
    - name: enable-oauth
      metadata:
        annotations:
          vault.hashicorp.com/agent-inject: "true"
          vault.hashicorp.com/role: "k8s-secrets"
          vault.hashicorp.com/agent-inject-secret-harbor-creds: "k8s/data/secrets/harbor"
          vault.hashicorp.com/agent-inject-template-harbor-creds: |
            {{ with secret "k8s/data/secrets/harbor" -}}
              export harborUser={{ .Data.data.username }}
              export harborPass={{ .Data.data.password }}
            {{- end }}
          vault.hashicorp.com/agent-inject-secret-server-url: "k8s/data/configs/server-url"
          vault.hashicorp.com/agent-inject-template-server-url: |
            {{ with secret "k8s/data/configs/server-url" -}}
              export serverUrl={{ .Data.data.url }}
            {{- end }}
          vault.hashicorp.com/agent-inject-secret-oauth-creds: "k8s/data/oauth/creds"
          vault.hashicorp.com/agent-inject-template-oauth-creds: |
            {{ with secret "k8s/data/oauth/creds" -}}
              export oauth_harbor={{ .Data.data.harbor }}
              export oauth_tenant_id={{ .Data.data.tenantid }}
              export oauth_client_id={{ .Data.data.clientid }}
            {{- end }}
      container:
        image: alpine/k8s:1.13.12
        command: [sh, -c]
        args: 
          - |
            for f in /vault/**/*; do source $f; done;
            curl -X PUT -u "$harborUser:$harborPass" "https://$serverUrl/api/v2.0/configurations" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{
              \"auth_mode\": \"oidc_auth\",
              \"oidc_name\": \"azure\",
              \"oidc_endpoint\": \"https://login.microsoftonline.com/$oauth_tenant_id/v2.0\",
              \"oidc_client_id\": \"$oauth_client_id\",
              \"oidc_client_secret\": \"$oauth_harbor\",
              \"oidc_scope\": \"openid,profile,email\"
              }" 