apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tooling-terraform-base-tp
  namespace: argo
spec:
  entrypoint: terraform-base
  templates:
  - name: terraform-base
    inputs:
      artifacts:
      - name: terraform-folder
        path: /src
      parameters:
      - name: sp-secret-name
        default: service-principal
      - name: terraform-path
      - name: action
      - name: args
    container: 
      image: hashicorp/terraform
      command: ["/bin/sh", "-c"]
      args:
       - terraform {{inputs.parameters.action}} {{inputs.parameters.args}} {{inputs.parameters.terraform-path}}
      workingDir: /src/terraform
      env:
      - name: ARM_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: '{{inputs.parameters.sp-secret-name}}'
            key: sp_client_id
      - name: ARM_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: '{{inputs.parameters.sp-secret-name}}'
            key: sp_client_secret
      - name: ARM_SUBSCRIPTION_ID
        valueFrom:
          secretKeyRef:
            name: '{{inputs.parameters.sp-secret-name}}'
            key: sp_subscription_id
      - name: ARM_TENANT_ID
        valueFrom:
          secretKeyRef:
            name: '{{inputs.parameters.sp-secret-name}}'
            key: sp_tenant_id
    outputs:
      artifacts:
      - name: terraform-folder
        optional: true
        path: '/src'
      - name: kube-config
        optional: true
        path: '/src/terraform/config'
      - name: values
        optional: true
        path: '/src/terraform/values'
      parameters:
      - name: fqdn
        valueFrom:
          default: ''
          path: '/src/terraform/fqdn'