apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tooling-terraform-wf-tp
  namespace: argo
spec:
  entrypoint: terraform-workflow
  podGC:
    strategy: OnWorkflowSuccess
  arguments:
    parameters:
      - name: environment_name
        value: dev
      - name: sp-secret-name
        value: dataplatform-dev
  templates:
  - name: terraform-workflow 
    inputs:
      parameters:
      - name: environment_name
        default: "{{workflow.parameters.environment_name}}"
      - name: resource_group_name
        default: service-aks-infrastructure-{{workflow.parameters.environment_name}}
      - name: storage_account_name
        default: servicetfstate{{workflow.parameters.environment_name}}
      - name: container_name
        default: terraformstate
      - name: key
        default: k8s.tfstate
      - name: sp-secret-name
        default: "{{workflow.parameters.sp-secret-name}}"
      - name: repo
        default: git@github.com:Open-Dataplatform/platform.git
    steps:
    - - name: git-clone-terraform
        templateRef:
          name: git-clone-template
          template: git-clone
        arguments:
          parameters:
          - name: ssh-url
            value: '{{inputs.parameters.repo}}'

      - name: infrastructure-check
        templateRef:
          name:  az-base-template
          template:  az-base
        arguments:
          parameters:
          - name: script
            value: |
              if [[ $(az storage account check-name -n {{inputs.parameters.storage_account_name}} --query "reason") != *"AlreadyExists"* ]] ;
              then
                echo "{{inputs.parameters.storage_account_name}} exists"
              else
                echo "{{inputs.parameters.storage_account_name}} does not exist.."
                
                echo "Creating {{inputs.parameters.resource_group_name}}"
                az group create -n {{inputs.parameters.resource_group_name}} -l westeurope
                
                echo "Creating {{inputs.parameters.storage_account_name}}"
                az storage account create -g {{inputs.parameters.resource_group_name}} -n {{inputs.parameters.storage_account_name}} -l westeurope --sku Standard_LRS
                az storage container create -n terraformstate --account-name {{inputs.parameters.storage_account_name}}
              fi
          - name: sp-secret-name
            value: '{{inputs.parameters.sp-secret-name}}'

    - - name: azure-terraform-init
        templateRef:
          name: tooling-terraform-base-tp
          template: terraform-base
        arguments:
          parameters:
          - name: action
            value: init
          - name: args
            value: -backend-config="storage_account_name={{inputs.parameters.storage_account_name}}" -backend-config="container_name={{inputs.parameters.container_name}}" -backend-config="key={{inputs.parameters.key}}" -backend-config="resource_group_name={{inputs.parameters.resource_group_name}}" 
          - name: terraform-path
            value: ./azure
          - name: sp-secret-name
            value: '{{inputs.parameters.sp-secret-name}}'
          artifacts:
          - name: terraform-folder
            from: "{{steps.git-clone-terraform.outputs.artifacts.repo}}"

    - - name: azure-terraform-plan
        templateRef:
          name: tooling-terraform-base-tp
          template: terraform-base
        arguments:
          parameters:
          - name: action
            value: plan
          - name: args
            value: '-lock=false -var=environmentName={{inputs.parameters.environment_name}}'
          - name: terraform-path
            value: ./azure
          - name: sp-secret-name
            value: '{{inputs.parameters.sp-secret-name}}'
          artifacts:
          - name: terraform-folder
            from: "{{steps.azure-terraform-init.outputs.artifacts.terraform-folder}}"

    - - name: azure-terraform-apply
        templateRef:
          name: tooling-terraform-base-tp
          template: terraform-base
        arguments:
          parameters:
            - name: action
              value: apply
            - name: args
              value: "-auto-approve -var=environmentName={{inputs.parameters.environment_name}}"
            - name: terraform-path
              value: ./azure
            - name: sp-secret-name
              value: '{{inputs.parameters.sp-secret-name}}'
          artifacts:
            - name: terraform-folder
              from: "{{steps.azure-terraform-init.outputs.artifacts.terraform-folder}}"

    outputs:
      artifacts:
      - name: kube-config
        from: '{{steps.azure-terraform-apply.outputs.artifacts.kube-config}}'
      - name: values
        from: '{{steps.azure-terraform-apply.outputs.artifacts.values}}'
      parameters:
      - name: fqdn
        valueFrom:
          parameter: '{{steps.azure-terraform-apply.outputs.parameters.fqdn}}'
      - name: fqdn_vault
        valueFrom:
          parameter: '{{steps.azure-terraform-apply.outputs.parameters.fqdn_vault}}'