apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: service-cluster-deployment-template
  namespace: argo
spec:
  entrypoint: service-cluster-deployment
  podGC:
    strategy: OnWorkflowSuccess
  arguments:
    parameters:
    - name: environmentName
      value: mht
  templates:
  - name: service-cluster-deployment 
    steps:
    - - name: terraform
        templateRef:
          name: terraform-workflow-template
          template: terraform-workflow
        arguments:
          parameters:
          - name: environmentName
            value: mht

      - name: clone-argo-cd
        templateRef:
          name: git-clone-template
          template: git-clone
        arguments:
          parameters:
          - name: ssh-url
            value: git@github.com:Open-Dataplatform/tooling-argo-cd.git
      
      - name: clone-ingress-nginx
        templateRef:
          name: git-clone-template
          template: git-clone
        arguments:
          parameters:
          - name: ssh-url
            value: git@github.com:Open-Dataplatform/k8s-ingress-nginx.git

    - - name: helm-ingress-nginx
        templateRef:
          name: helm-base-template
          template: helm-base
        arguments:
          parameters:
          - name: action
            value: 'install'
          - name: args
            value: 'ingress-nginx ./.helm'
          - name: namespace
            value: 'ingress-nginx'
          artifacts:
          - name: kube-config
            from: '{{steps.terraform.outputs.artifacts.kube-config}}'
          - name: chart
            from: '{{steps.clone-ingress-nginx.outputs.artifacts.repo}}'
      
      - name: helm-argo-cd
        templateRef:
          name: helm-base-template
          template: helm-base
        arguments:
          parameters:
          - name: action
            value: 'install'
          - name: args
            value: 'argo-cd ./.helm'
          - name: namespace
            value: 'argo-cd'
          - name: value-override
            value: '--set server.ingress.hosts[0]={{steps.terraform.outputs.parameters.dns-name}}.westeurope.cloudapp.azure.com'
          artifacts:
          - name: kube-config
            from: '{{steps.terraform.outputs.artifacts.kube-config}}'
          - name: chart
            from: '{{steps.clone-argo-cd.outputs.artifacts.repo}}'