apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: event-git-docker
  namespace: argo
spec:
  event:
    selector: |
      metadata["x-github-event"] == ["push"]
      && (any(payload.commits, { any(.modified, {# contains ".docker"}) }) 
          || any(payload.commits, { any(.added, {# contains ".docker"}) }) )
  submit:
    workflowTemplateRef:
      name: docker-build-workflow-template
    arguments:
      parameters:
      - name: ssh-url
        valueFrom:
          event: payload.repository.ssh_url
      - name: repo-name
        valueFrom:
          event: payload.repository.name
