apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: add-helm-harbor-workflow-template
  namespace: argo
spec:
  entrypoint: workflow
  podGC:
    strategy: OnWorkflowSuccess
  templates:
  - name: workflow
    inputs:
      parameters:
      - name: ssh-url
      - name: repo-name
    steps:
    - - name: git-clone-repo
        templateRef:
          name: git-clone-template
          template: git-clone
        arguments:
          parameters:
          - name: ssh-url
            value: "{{inputs.parameters.ssh-url}}"