apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-sc-deployment-destruction-wf
spec:
  schedule: "@daily"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: cron-steps
    templates:
    - name: cron-steps
      steps:
      - - name: gen-epoch-time
          templateRef:
            name: utility-gen-date-for-cron-job
            template: gen-date
      - - name: service-cluster-deployment
          templateRef:
            name: service-cluster-deployment-template
            template: service-cluster-deployment
          arguments:
            parameters:
            - name: environment_name
              value: "cron{{steps.gen-epoch-time.outputs.result}}"

      - - name: delay
          template: delay

      - - name: service-cluster-destruction
          templateRef:
            name: tooling-terraform-destroy-platform-wf-tp
            template: terraform-workflow
          arguments:
            parameters:
            - name: environment_name
              value: "cron{{steps.gen-epoch-time.outputs.result}}"
            - name: resource_group_name
              value: service-aks-infrastructure-cron{{steps.gen-epoch-time.outputs.result}}
            - name: storage_account_name
              value: servicetfstatecron{{steps.gen-epoch-time.outputs.result}}

    - name: delay
      suspend:
        duration: "15m"    # Must be a string. Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h", "1d"