apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: az-base-template
  namespace: argo
spec:
  entrypoint: az-base
  templates:
  - name: az-base
    volumes:
    - name: azure-backend-secret
      secret:
        secretName: azure-backend-conf
    inputs:
      parameters:
      - name: script
    container:
      volumeMounts:
      - name: azure-backend-secret
        mountPath: "/secrets/"
        readOnly: true
      image: mcr.microsoft.com/azure-cli
      command: ["/bin/sh", "-c"]
      args: 
        - |
          source /secrets/azurebackend.conf
          az login --service-principal -u $sp_client_id -p $sp_client_secret --tenant $sp_tenant_id --output none;

          {{inputs.parameters.script}} 
      env:
      - name: sp_client_id
        valueFrom:
          secretKeyRef:
            name: service-principal
            key: sp_client_id
      - name: sp_client_secret
        valueFrom:
          secretKeyRef:
            name: service-principal
            key: sp_client_secret
      - name: sp_tenant_id
        valueFrom:
          secretKeyRef:
            name: service-principal
            key: sp_tenant_id