apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: az-base-template
  namespace: argo
spec:
  entrypoint: az-base
  templates:
  - name: az-base
    inputs:
      parameters:
      - name: script
      - name: sp-secret-name
        default: service-principal
    container:
      image: mcr.microsoft.com/azure-cli
      command: ["/bin/sh", "-c"]
      args: 
        - |
          az login --service-principal -u $sp_client_id -p $sp_client_secret --tenant $sp_tenant_id --output none;

          {{inputs.parameters.script}} 
      env:
      - name: sp_client_id
        valueFrom:
          secretKeyRef:
            name: '{{inputs.parameters.sp-secret-name}}'
            key: sp_client_id
      - name: sp_client_secret
        valueFrom:
          secretKeyRef:
            name: '{{inputs.parameters.sp-secret-name}}'
            key: sp_client_secret
      - name: sp_tenant_id
        valueFrom:
          secretKeyRef:
            name: '{{inputs.parameters.sp-secret-name}}'
            key: sp_tenant_id