apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: az-base-template
  namespace: argo
spec:
  entrypoint: az-base
  arguments:
    parameters:
      - name: sp-secret-name
        value: service-principal
  templates:
  - name: az-base
    inputs:
      parameters:
      - name: script
      - name: sp-secret-name
        default: service-principal
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "k8s-secrets"
        vault.hashicorp.com/agent-inject-secret-service-principal: "k8s/data/service-principals/{{inputs.parameters.sp-secret-name}}"
        vault.hashicorp.com/agent-inject-template-service-principal: |
          {{ with secret "k8s/data/service-principals/{{inputs.parameters.sp-secret-name}}" -}}
            export sp_client_id="{{ .Data.data.clientid }}"
            export sp_client_secret="{{ .Data.data.clientsecret }}"
            export sp_subscription_id="{{ .Data.data.subscriptionid }}"
            export sp_tenant_id="{{ .Data.data.tenantid }}"
          {{- end }}
    container:
      image: mcr.microsoft.com/azure-cli
      command: ["/bin/sh", "-c"]
      args: 
        - |
          for f in /vault/secrets/*; do source $f; done;
          az login --service-principal -u $sp_client_id -p $sp_client_secret --tenant $sp_tenant_id --output none;
          az account set --subscription $sp_subscription_id

          {{inputs.parameters.script}}