apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: helm-workflow-template
  namespace: argo
spec:
  entrypoint: helm-workflow
  podGC:
    strategy: OnWorkflowSuccess
  templates:
  - name: helm-workflow 
    inputs:
      parameters:
      - name: ssh-url
      - name: context
      - name: service
      - name: namespace
      - name: values-tp-file-name
      - name: valuesScript
        default: ' '
      artifacts:
      - name: values
      - name: kube-config
    steps:
    - - name: template-value-file
        templateRef:
          name: tooling-j2cli-wf-tp
          template: j2cli-wf
        arguments:
          parameters:
          - name: repo
            value: '{{inputs.parameters.ssh-url}}'
          - name: values-tp-file-name
            value: '{{inputs.parameters.values-tp-file-name}}'
          artifacts:
          - name: values
            from: '{{inputs.artifacts.values}}'
    
    - - name: helm-install
        templateRef:
          name: helm-base-template
          template: helm-base
        arguments:
          parameters:
          - name: action
            value: 'upgrade'
          - name: args
            value: "{{inputs.parameters.context}}-{{inputs.parameters.service}} ./.helm"
          - name: flags
            value:
              '
              {{inputs.parameters.valuesScript}}
              --namespace {{inputs.parameters.namespace}}
              --create-namespace
              --install
              '
          artifacts:
          - name: kube-config
            from: '{{inputs.artifacts.kube-config}}'
          - name: chart
            from: '{{steps.template-value-file.outputs.artifacts.repo}}'
          - name: value
            optional: true
            from: '{{steps.template-value-file.outputs.artifacts.value-file}}'