apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tooling-vault-logged-in-url-template
  namespace: argo
spec:
  entrypoint: vault-logged-in-url
  templates:
    - name: vault-logged-in-url
      metadata:
        annotations:
          vault.hashicorp.com/agent-inject: "true"
          vault.hashicorp.com/role: "k8s-secrets"
          vault.hashicorp.com/agent-inject-secret-vault_token: "k8s/data/secrets/vault"
          vault.hashicorp.com/agent-inject-template-vault_token: |
            {{- with secret "k8s/data/secrets/vault" -}}
              export roottoken="{{ .Data.data.root_token }}"
            {{- end -}}
      inputs:
        parameters:
        - name: script
        artifacts:
        - name: jq
          path: /bin/jq
          mode: 0755
          http:
            url: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
      container:
        image: hashicorp/vault
        command:
          - "/bin/sh"
          - "-c"
        args:
          - >
            for f in /vault/secrets/*; do source $f; done;
            export VAULT_ADDR="http://tooling-vault.vault.svc.cluster.local:8200";
            vault login -no-print=true $roottoken;
            {{inputs.parameters.script}}
      